"""add user, market, user interest tables

Revision ID: 211e9d09101d
Revises: 9d4f230d7d10
Create Date: 2026-06-21 19:33:41.257997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '211e9d09101d'
down_revision: Union[str, Sequence[str], None] = '9d4f230d7d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_ko', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_users_provider_account')
    )
    op.create_table('user_interest_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'market_id', name='uq_user_interest_market')
    )
    op.create_index(op.f('ix_user_interest_markets_user_id'), 'user_interest_markets', ['user_id'], unique=False)
    op.create_table('user_interest_sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sector_id', name='uq_user_interest_sector')
    )
    op.create_index(op.f('ix_user_interest_sectors_user_id'), 'user_interest_sectors', ['user_id'], unique=False)
    op.create_table('user_interest_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_entities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_interest_company')
    )
    op.create_index(op.f('ix_user_interest_companies_user_id'), 'user_interest_companies', ['user_id'], unique=False)
    # 시장 시드 — 국내만 활성, 해외는 데이터 준비 전까지 비활성(온보딩 노출 제외).
    op.bulk_insert(
        sa.table(
            'markets',
            sa.column('code', sa.String),
            sa.column('name_ko', sa.String),
            sa.column('name_en', sa.String),
            sa.column('is_active', sa.Boolean),
        ),
        [
            {'code': 'KR', 'name_ko': '국내', 'name_en': 'Domestic', 'is_active': True},
            {'code': 'OVERSEAS', 'name_ko': '해외', 'name_en': 'Overseas', 'is_active': False},
        ],
    )
    # autogenerate가 ORM 모델 없는 기존 테이블(issue_docent·news_analysis, 섹션 06·07 영역)을
    # drop 대상으로 잡았으나 의도된 스키마라 제거했다. 본 마이그레이션은 추가 전용.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # upgrade에서 추가한 테이블만 되돌린다(issue_docent·news_analysis는 본 마이그레이션 소관 아님).
    op.drop_index(op.f('ix_user_interest_companies_user_id'), table_name='user_interest_companies')
    op.drop_table('user_interest_companies')
    op.drop_index(op.f('ix_user_interest_sectors_user_id'), table_name='user_interest_sectors')
    op.drop_table('user_interest_sectors')
    op.drop_index(op.f('ix_user_interest_markets_user_id'), table_name='user_interest_markets')
    op.drop_table('user_interest_markets')
    op.drop_table('users')
    op.drop_table('markets')
    # ### end Alembic commands ###
