"""add news_cluster run_date rep unique constraint

(run_date, representative_news_id) 유니크 — persist_clusters가 ON CONFLICT DO NOTHING으로
재실행(재시도) 시 같은 클러스터를 중복 적재하지 않게 하는 멱등 키(설계 01 §2, 코드리뷰 #1).
기존 데이터는 1회 실행분뿐이라 중복 키 없음 확인 후 추가.

Revision ID: 372d8c66317e
Revises: 52b04bf7383d
Create Date: 2026-06-11 21:57:22.204888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372d8c66317e'
down_revision: Union[str, Sequence[str], None] = '52b04bf7383d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_news_cluster_run_rep', 'news_cluster', ['run_date', 'representative_news_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_news_cluster_run_rep', 'news_cluster', type_='unique')
    # ### end Alembic commands ###
