"""add news_cluster table and missing news indexes

baseline(e91033167c44) 생성 시점에 ORM에 없던 news_cluster 테이블(클러스터링 산출물,
설계 02 §8.3)과 news 인덱스 2개가 DB에 누락돼 있었다 — autogenerate 드리프트 체크로 발견.
EmbeddingClusterer(persist_clusters)가 news_cluster에 적재하므로 실행 전 필수.

- ix_news_embedding: HNSW(cosine). m=16·ef_construction=64는 pgvector 기본값(설계 05 §3.1과
  동일). 벡터가 쌓이기 전 미리 생성한다(누적 후 빌드는 오래 걸림).
- ix_news_unanalyzed: 미분석분 최신순 조회용 partial 인덱스(설계 02 §8.2).

Revision ID: 52b04bf7383d
Revises: c6fd3e4b6185
Create Date: 2026-06-11 20:48:47.094279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b04bf7383d'
down_revision: Union[str, Sequence[str], None] = 'c6fd3e4b6185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('representative_news_id', sa.Integer(), nullable=False),
    sa.Column('member_news_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['representative_news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_embedding', 'news', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_news_unanalyzed', 'news', ['is_analyzed', sa.literal_column('published_at DESC NULLS LAST')], unique=False, postgresql_where=sa.text('is_analyzed = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_unanalyzed', table_name='news', postgresql_where=sa.text('is_analyzed = false'))
    op.drop_index('ix_news_embedding', table_name='news', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('news_cluster')
    # ### end Alembic commands ###
