"""add news created_at index

Revision ID: 55d278ba5941
Revises: 372d8c66317e
Create Date: 2026-06-11 23:11:30.515316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d278ba5941'
down_revision: Union[str, Sequence[str], None] = '372d8c66317e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_news_created_at', 'news', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_created_at', table_name='news')
    # ### end Alembic commands ###
