"""baseline current schema

Revision ID: e91033167c44
Revises: 
Create Date: 2026-06-09 10:48:21.823136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e91033167c44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector 확장 — embedding 컬럼(Vector)이 의존한다. 테이블 생성 전 먼저 활성화.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rcept_no', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('corp_name', sa.String(length=200), nullable=False),
    sa.Column('corp_code', sa.String(length=20), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=True),
    sa.Column('disclosure_type', sa.String(length=50), nullable=False),
    sa.Column('disclosed_at', sa.DateTime(), nullable=False),
    sa.Column('is_analyzed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rcept_no')
    )
    op.create_index(op.f('ix_disclosures_corp_code'), 'disclosures', ['corp_code'], unique=False)
    op.create_index('ix_disclosures_embedding', 'disclosures', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corp_code', sa.String(length=20), nullable=False),
    sa.Column('corp_name', sa.String(length=200), nullable=False),
    sa.Column('rcept_no', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('operating_income', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corp_code', 'year', 'quarter', name='uq_financial_statement')
    )
    op.create_index(op.f('ix_financial_statements_rcept_no'), 'financial_statements', ['rcept_no'], unique=False)
    op.create_table('market_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_type', 'currency', 'date', name='uq_market_indicator', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_market_indicators_date'), 'market_indicators', ['date'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('rss_source', sa.String(length=100), nullable=False),
    sa.Column('news_source', sa.String(length=100), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('preprocessed_at', sa.DateTime(), nullable=True),
    sa.Column('is_filtered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_analyzed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_news_stock_code', 'news', ['stock_code'], unique=False, postgresql_where=sa.text('stock_code IS NOT NULL'))
    op.create_table('report_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corp_code', sa.String(length=20), nullable=False),
    sa.Column('corp_name', sa.String(length=200), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('rcept_no', sa.String(length=20), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('subsection', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corp_code', 'report_year', 'chunk_type', 'subsection', name='uq_report_chunk')
    )
    op.create_index('ix_report_chunks_embedding', 'report_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_report_chunks_rcept_no'), 'report_chunks', ['rcept_no'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ko', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('wics_code', sa.String(length=10), nullable=False),
    sa.Column('gics_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gics_code'),
    sa.UniqueConstraint('name_ko'),
    sa.UniqueConstraint('wics_code')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'date', name='uq_stock_code_date')
    )
    op.create_index(op.f('ix_stock_prices_date'), 'stock_prices', ['date'], unique=False)
    op.create_table('company_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('name_ko', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('corp_code', sa.String(length=20), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code')
    )
    op.create_index(op.f('ix_company_entities_sector_id'), 'company_entities', ['sector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_entities_sector_id'), table_name='company_entities')
    op.drop_table('company_entities')
    op.drop_index(op.f('ix_stock_prices_date'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_report_chunks_rcept_no'), table_name='report_chunks')
    op.drop_index('ix_report_chunks_embedding', table_name='report_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('report_chunks')
    op.drop_index('ix_news_stock_code', table_name='news', postgresql_where=sa.text('stock_code IS NOT NULL'))
    op.drop_table('news')
    op.drop_index(op.f('ix_market_indicators_date'), table_name='market_indicators')
    op.drop_table('market_indicators')
    op.drop_index(op.f('ix_financial_statements_rcept_no'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index('ix_disclosures_embedding', table_name='disclosures', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_disclosures_corp_code'), table_name='disclosures')
    op.drop_table('disclosures')
    # ### end Alembic commands ###
