"""add industry_group and industry tables

Revision ID: fa6e579bc7dc
Revises: 55d278ba5941
Create Date: 2026-06-16 15:14:03.816429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6e579bc7dc'
down_revision: Union[str, Sequence[str], None] = '55d278ba5941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('name_ko', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('gics_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gics_code')
    )
    op.create_index(op.f('ix_industry_groups_sector_id'), 'industry_groups', ['sector_id'], unique=False)
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry_group_id', sa.Integer(), nullable=False),
    sa.Column('name_ko', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('gics_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['industry_group_id'], ['industry_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gics_code')
    )
    op.create_index(op.f('ix_industries_industry_group_id'), 'industries', ['industry_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_industries_industry_group_id'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_industry_groups_sector_id'), table_name='industry_groups')
    op.drop_table('industry_groups')
    # ### end Alembic commands ###
